### PR TITLE
~/.ssh/config source

### PR DESCRIPTION
**Pull request by gizmomogwai**
hi .. i have a lot of hosts in my ~/.ssh/config. sometimes i even have the same host but with different users in config, so the known host source, is not picking those up.
for this i created a simple source, that hardcoded uses ~/.ssh/config to scan through Host entries and puts them to your excellent remote hosts plugin.

in the process i also updated the xcode project files. this makes the change a little bigger than it must be.

### CODE REVIEW

**Comment by skurfer** [comment]
Thanks for the contribution. There are a couple of things to address before I can merge it though.

First, a couple of small things in the property list: The build number shouldn’t jump quite so far. (I know `bltrversion` does this for you. I usually manually set it back when things look good.) And I’m not sure if this source should be enabled by default, but maybe. It depends on what we can come up with for handling duplicates, which I’ll mention in a minute.

The main problems are:

  1. The `Host` lines don’t just contain hostnames or FQDNs. They can contain one or more *patterns*.
  2. There can be more than one pattern on a single line (separated by whitespace).
  3. If a host is listed in both `~/.ssh/config` and `~/.hosts` (or some other file), the latter should take precedence. Mainly because those files support metadata that could be clobbered, depending on the order entries are scanned.

So the most obvious fix is to split each match on whitespace to get multiple hosts.

For the wildcard patterns, I don’t think we can do anything useful, so they should probably just be thrown out. There’s code to check for valid hostnames starting on line 86 of `RemoteHostsSource.m`. (Code that was written before `NSRegularExpression` existed, obviously.) Maybe that can be broken out into a more general purpose function and used here as well.

For the duplicates, it should be easy enough to just figure out the identifier, then check the catalog with `[QSLib objectWithIdentifier:ident]` and skip anything that exists.

FYI, I’ve thought about adding this feature in the past, but my config is almost entirely wildcards and I assumed that was the case for most people, so I never bothered. :smiley:

**Comment by gizmomogwai** [comment]
Thanks for the feedback and for considering this patch at all.

I would suggest the following to clean the stuff up a little bit:
- I revert the changes in the project-files (i keep only the added sources).
- I disable the source by default
- I check the entries to be valid hostnames (some extract method should be enough i think without looking at the code).
- I don't add entries, if they are already there.

I did not know about the wildcards ... could you give me an example?

**Comment by skurfer** [comment]
> I revert the changes in the project-files (i keep only the added sources).

Yes, I forgot to mention these. Deleting anything in bold from the Build Settings usually gets things set the way they should be.

I don’t think you need to disable the entry by default *and* ignore duplicates. Just ignoring duplicates should make it acceptable to enable the thing all the time. (Unlike `known_hosts`, the config file contains hosts you actually care about.)

> I did not know about the wildcards ... could you give me an example?

Here’s an actual entry from my config:

    Host *qsapp.com quicksilver.sixfeetup.com

That matches anything ending with “qsapp.com” and one specific FQDN. You can also use `?` to match a single character and `!` to negate matches. It’s very common for people to have a section of their config that begins with `Host *` so they can apply certain settings to all connections. You can read about it in detail by running `man ssh_config`, but in practice, if you just ignore everything that isn’t a valid hostname or FQDN, it should work.

**Comment by gizmomogwai** [comment]
I started implementing the discussed changes.
One strange thing (probably a quicksilver speciality):
When I put in a predicate to remove duplicates with your proposed api, I think whats happening for a refresh is, that the qslib request is used against the current set of QSObjects (this means I filter out all entries I find) -> after the refresh my lists is empty. If I now refresh the list again, the current list is empty, so all my QSObjects are again put into the list.

Is there anything I can do, to work around this?

**Comment by skurfer** [comment]
Yeah, that was bad advice. Anything not returned by a catalog entry (that belongs to it) will be removed from the catalog.

There are many things we could do about this. We could see which object source the existing object came from, but that could be expensive and I worry about hitting the catalog too much from a background thread as it’s supposedly getting updated. A “dumb”, but safe and fast check would be to just see if the object has any metadata. Something like:

```obj-c
QSObject *existingObject = [QSLib objectWithIdentifier:ident];
if ([[existingObject meta] count]) {
    continue;
}
```

If it *does* have metadata, we know it came from another source and we should skip it. If not, maybe it came from another source, maybe it came from this one, but there’s probably no harm in replacing it.

**Comment by gizmomogwai** [comment]
hi rob,

thanks for helping me with this.
strangely my qsobjects do not respond to the meta selector.
what kind of metadata are you talking about? perhaps the idea of having another source is not so good after all. our main problem is, that the hosts file could add an entry as well as the ssh-config file.
could we come up with a count, that spans over both sources, that would signify, if an entry was from the last scan run, or the current one?

**Comment by skurfer** [comment]
> strangely my qsobjects do not respond to the meta selector.

That is strange. Is it just a code completion issue, or will it not build/run?

> what kind of metadata are you talking about?

Things like OS type, custom icons, groups, etc.

It’s described in [the plug-in’s documentation][1]. Start with “The hostname or FQDN should be the first thing on each line, but other metadata is allowed (separated by a single space).”

> our main problem is, that the hosts file could add an entry as well as the ssh-config file.
could we come up with a count, that spans over both sources, that would signify, if an entry was from the last scan run, or the current one?

That seems like a lot of code for something so simple. If we can get the `meta` test to work, it should be easy to implement, and it should run much faster.

[1]: /quicksilver/RemoteHosts-qsplugin/blob/master/Documentation.mdown

**Comment by gizmomogwai** [comment]
hi rob,

thanks again for your newest feedback. i read the documentation you sent me.
it seems that you are using .hosts heavily ... it really has some cool features like e.g. the groups. really handy. i think we really should make sure, that we do not overwrite those entries by chance!
unfortunately meta is not in the current api. if i just ignore the compile time warning, i get a runtime exception, that the object is not responding to the selector meta (on the first object i try to deduplicate). if i first check if the qsobject thats a duplication candidate responds to the selector meta, i always get false.

the last thing that i tried is, that i added a meta data to the RemoteHostsSource for the meta id @"source" with the origin of the entry. this i can test in the SshConfigSource. Would this be a viable option for you?

**Comment by skurfer** [comment]
> unfortunately meta is not in the current api.

Ah, you’re right. I was just looking through `QSObject.h` for things we could use, but I suppose not all of that is exposed publicly.

> the last thing that i tried is, that i added a meta data to the RemoteHostsSource for the meta id @"source" with the origin of the entry. this i can test in the SshConfigSource. Would this be a viable option for you?

That seems like a reasonable approach. I’ve tested it and it seems to work. I only end up with two hosts from your new source. One problem is that the FQDN is being added to the catalog for all hosts, instead of just the hostname, which is a bit “noisy” for my taste. The documentation also needs to be updated.

I can take care of those things though. Thanks again for the contribution.

If there’s anything annoying you in the core application, please feel free to take a stab at that as well. :smiley:

**Comment by gizmomogwai** [comment]
thanks for putting my commit through. i still wonder, if i did some stuff wrong regarding memory/memory-pools. i am a bit rusty in regard to this whole cocoa thing, and i saw, that the "new" objective-c has e.g. @autoreleasepool {}. if one source would e.g. leak memory, would qs cope with this, or would this really leak?

**Comment by skurfer** [comment]
The call to `objectsForEntry:` is already wrapped in `@autoreleasepool`, so there’s no need to do it in the individual sources. I’m going to convert this plug-in to ARC as well before releasing an update, so chances of such mistakes will go down.

**Pull request merged**
